/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visaoCalculos;
import entidades.Paralelepipedo;
import javax.swing.JOptionPane;
/**
 *
 * @author filip
 */
public class calcularParalelepipedo extends javax.swing.JInternalFrame {

    /**
     * Creates new form calcularParalelepipedo
     */
    public calcularParalelepipedo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelTitulo = new javax.swing.JLabel();
        JLabelAltura = new javax.swing.JLabel();
        JLabelComprimento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTextField_Altura = new javax.swing.JTextField();
        JTextField_Comprimento = new javax.swing.JTextField();
        JTextField_Largura = new javax.swing.JTextField();
        JButton_Executar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextArea_Saida = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);

        JLabelTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JLabelTitulo.setText("Cálculos para Paralelepípedos");

        JLabelAltura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLabelAltura.setText("Altura:");

        JLabelComprimento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JLabelComprimento.setText("Comprimento:");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Largura:");

        JTextField_Altura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        JTextField_Comprimento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        JTextField_Largura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        JButton_Executar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JButton_Executar.setText("Executar");
        JButton_Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ExecutarActionPerformed(evt);
            }
        });

        JTextArea_Saida.setColumns(20);
        JTextArea_Saida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JTextArea_Saida.setRows(5);
        jScrollPane1.setViewportView(JTextArea_Saida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelComprimento)
                        .addGap(18, 18, 18)
                        .addComponent(JTextField_Comprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelAltura)
                        .addGap(18, 18, 18)
                        .addComponent(JTextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JButton_Executar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(JTextField_Largura, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabelTitulo)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelAltura)
                    .addComponent(JTextField_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelComprimento)
                    .addComponent(JTextField_Comprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTextField_Largura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JButton_Executar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ExecutarActionPerformed
     try{
             Paralelepipedo p1 = new Paralelepipedo();
      
      p1.setAltura(Integer.parseInt(JTextField_Altura.getText()));
      p1.setComprimento(Integer.parseInt(JTextField_Comprimento.getText()));
      p1.setLargura(Integer.parseInt(JTextField_Largura.getText()));
      
      JTextArea_Saida.setText("Volume: " + p1.calcularVolume() + "\n Área: " + p1.calcularArea());
     }
     catch(Exception erro){
        JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    
    }//GEN-LAST:event_JButton_ExecutarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Executar;
    private javax.swing.JLabel JLabelAltura;
    private javax.swing.JLabel JLabelComprimento;
    private javax.swing.JLabel JLabelTitulo;
    private javax.swing.JTextArea JTextArea_Saida;
    private javax.swing.JTextField JTextField_Altura;
    private javax.swing.JTextField JTextField_Comprimento;
    private javax.swing.JTextField JTextField_Largura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
